### ISSUE TITLE
StapeSGTM has no construct signatures - TS Error

### ISSUE THREAD

**Issue by margolisj** [stape-io/stape-sgtm-nodejs#3]
```
  Type 'typeof import("/Users/xxxxxxx/api/node_modules/.pnpm/stape-sgtm-nodejs@1.0.1/node_modules/stape-sgtm-nodejs/dist/esm/index")' has no construct signatures.
```

Could be my TS setup but I'm unable to get the types correctly. 

TSConfig:
```
{
  "compilerOptions": {
    "target": "ESNext",
    "useDefineForClassFields": true,
    "lib": ["ES2020"]
    "module": "NodeNext",
    "skipLibCheck": true,
    "outDir": "./dist",
    "types": [
      "node",
    ],

    "baseUrl": "./src",

    "moduleResolution": "NodeNext",
}
```

**Comment by margolisj** [comment]
Also, just to add, is this currently working for server to server gtag events using a Stape server? Is the `request_path: '/data'` the standard value to fire events?

**Comment by kHorozhanov** [comment]
Hi @margolisj, thanks for reporting this issue!
I have created a new project with the tsconfig.json you provided, and I don't see any issues with stape-sgtm-nodejs.
Please provide an example of when I can see the problem. It would be great if you could create a repo with it. Thanks.

**Comment by kHorozhanov** [comment]
> Also, just to add, is this currently working for server to server gtag events using a Stape server? Is the `request_path: '/data'` the standard value to fire events?

`/data` path is the default path for our [Data Client](https://github.com/stape-io/data-client).
Regarding gtag server to server - could you please elaborate on the entire flow you envision? 
Default path for GA4 Client is /collect, however it would only digest gtag hits properly formed by the client-side gtag library.
There’s also measurement protocol which is the only ‘true s2s’ in the gtag context, but that one is very limited in terms of possible payloads
